version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
    networks:
      - fullstack


  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/build"
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
